### ISSUE TITLE
Run Error: context mismatch

### ISSUE THREAD

**Issue by CrazybinaryLi** [wx-csy/python-brahma#1]
When running scripts(sample.py,test.py,cli.py) with python3, encounter error: z3.z3types.Z3Exception: context mismatch.

**Comment by wx-csy** [comment]
This is probably because Z3 fails to deduce the variable context in some older Z3 versions. You may either update your Z3 or add a patch like https://github.com/wx-csy/python-brahma/commit/91c061072b568130b7e61ab765a369d57e0a89f4.

**Comment by CrazybinaryLi** [comment]
Yes, update z3 to version 4.12.2.0, it works.

**Comment by CrazybinaryLi** [comment]
For the example in sample.py: y==a+2*b, the result of synthesis is 
def f(x0, x1):
    v0 = x0 + x1
    v5 = ~x1
    v6 = v0 - 1
    v7 = v6 - v5
    return v7
The result is wrong?

**Comment by wx-csy** [comment]
> For the example in sample.py: y==a+2*b, the result of synthesis is def f(x0, x1): v0 = x0 + x1 v5 = ~x1 v6 = v0 - 1 v7 = v6 - v5 return v7 The result is wrong?

I didn't get it wrong, but the result might not be as short as one may expect. The default component library contains a limited set of components; it doesn't contain constants like 2. To synthesize shorter results, one may augment the component library at the cost of potentially longer synthesizing time.
